import type { DashboardData } from './types';
import { formatMoney } from './analytics';
type AgentAnswer={answer:string;intent:string;caveats:string[];sources:string[]};
function findSector(q:string,d:DashboardData){const x=q.toLowerCase();return d.deals.bySector.find(s=>x.includes(s.name.toLowerCase()))}
export function answerQuestion(question:string,data:DashboardData):AgentAnswer{
 const q=question.toLowerCase().trim();const caveats:string[]=[];if(data.dataQuality.dealFlagged||data.dataQuality.workOrderFlagged)caveats.push(`${data.dataQuality.dealFlagged+data.dataQuality.workOrderFlagged} source rows carry explicit data-quality flags.`);const sources=['Skylark Command — Deals','Skylark Command — Work Orders'];const sector=findSector(q,data);
 if(/leadership|brief|update|meeting/.test(q))return{intent:'leadership_brief',sources,caveats,answer:`Leadership brief: ${data.deals.openCount+data.deals.onHoldCount} active/held opportunities represent ${formatMoney(data.deals.pipelineValue)} in pipeline, while won deals total ${formatMoney(data.deals.wonValue)}. Operations has ${data.workOrders.count} work orders: ${data.workOrders.completed} completed, ${data.workOrders.ongoing} ongoing/current-month, and ${data.workOrders.atRisk} explicitly at-risk. Receivables stand at ${formatMoney(data.workOrders.receivable)}. ${data.crossBoard.clientsWithOpenDealsAndActiveWork} clients currently have both active work and open/on-hold sales opportunities. Data-health score: ${data.dataQuality.score}%.`};
 if(/data quality|missing|null|dirty|health/.test(q))return{intent:'data_quality',sources,caveats,answer:`Data health is ${data.dataQuality.score}%. I evaluated ${data.dataQuality.totalRows} monday.com rows; ${data.dataQuality.dealFlagged} deal rows and ${data.dataQuality.workOrderFlagged} work-order rows carry explicit quality flags. Flagged records are retained and disclosed rather than silently dropped.`};
 if(/client|customer|cross|both boards/.test(q))return{intent:'cross_board',sources,caveats,answer:`${data.crossBoard.matchedClients} of ${data.crossBoard.totalWorkOrderClients} normalized work-order client codes match a client represented in Deals. ${data.crossBoard.clientsWithOpenDealsAndActiveWork} clients have both active operational work and an open/on-hold sales opportunity, making them useful accounts for leadership attention.`};
 if(/receivable|collection|billing|invoice/.test(q))return{intent:'collections',sources,caveats,answer:`Current work-order records show ${formatMoney(data.workOrders.billedValue)} billed (incl. GST), ${formatMoney(data.workOrders.collectedValue)} collected, and ${formatMoney(data.workOrders.receivable)} recorded as receivable. These figures are deterministic sums of usable monday.com numeric fields.`};
 if(/project|work order|operation|execution|delay|risk/.test(q))return{intent:'operations',sources,caveats,answer:`Across ${data.workOrders.count} work orders, ${data.workOrders.completed} are completed, ${data.workOrders.ongoing} are ongoing/current-month, ${data.workOrders.notStarted} are not started, and ${data.workOrders.atRisk} are explicitly marked pause/stuck/struck. I would prioritize the at-risk set, then review not-started work with near-term planned end dates.`};
 if(sector)return{intent:'sector_pipeline',sources,caveats,answer:`${sector.name} currently contributes ${formatMoney(sector.value)} across ${sector.count} open/on-hold opportunities in the available Deals board. That is ${data.deals.pipelineValue?Math.round(sector.value/data.deals.pipelineValue*100):0}% of active pipeline value.`};
 if(/pipeline|deal|sales|revenue|won/.test(q)){const top=data.deals.bySector[0];return{intent:'pipeline',sources,caveats,answer:`The available sales data contains ${data.deals.openCount} open and ${data.deals.onHoldCount} on-hold deals worth ${formatMoney(data.deals.pipelineValue)} in active pipeline. ${data.deals.wonCount} won deals represent ${formatMoney(data.deals.wonValue)}. ${top?`${top.name} is the largest active sector at ${formatMoney(top.value)}.`:''}`}}
 return{intent:'clarify',sources,caveats,answer:'I can analyze pipeline health, sector performance, won revenue, work-order execution, collections/receivables, cross-board client exposure, data quality, or prepare a leadership brief. Which business question should I focus on?'};
}
