import type { DashboardData, MondayItem } from './types';
const money=(v:string|undefined)=>{if(!v)return 0;const n=Number(v.replace(/[₹,\s]/g,''));return Number.isFinite(n)?n:0};
const norm=(v:string|undefined)=>(v||'').trim().toLowerCase();
const title=(v:string)=>v?v.replace(/\b\w/g,m=>m.toUpperCase()):'Unknown';
function groupMoney(items:MondayItem[],key:string){const map=new Map<string,{value:number;count:number}>();for(const item of items){const raw=item.fields[key]?.trim()||'Unknown';const cur=map.get(raw)||{value:0,count:0};cur.value+=money(item.fields['Masked Deal value']);cur.count++;map.set(raw,cur)}return [...map.entries()].map(([name,v])=>({name:title(name),...v})).sort((a,b)=>b.value-a.value)}
function groupCount(items:MondayItem[],key:string){const map=new Map<string,number>();for(const item of items){const raw=item.fields[key]?.trim()||'Unknown';map.set(raw,(map.get(raw)||0)+1)}return [...map.entries()].map(([name,count])=>({name:title(name),count})).sort((a,b)=>b.count-a.count)}
export function buildDashboard(dealsRaw:MondayItem[],workOrders:MondayItem[]):DashboardData{
 const deals=dealsRaw.filter(d=>{const s=norm(d.fields['Deal Status']);return d.name&&!d.name.startsWith('[Data Quality Row')&&s&&s!=='deal status'});
 const openDeals=deals.filter(d=>['open','on hold'].includes(norm(d.fields['Deal Status'])));const wonDeals=deals.filter(d=>norm(d.fields['Deal Status'])==='won');const activeWork=workOrders.filter(w=>norm(w.fields['Execution Status'])!=='completed');const atRisk=workOrders.filter(w=>/pause|stuck|struck/.test(norm(w.fields['Execution Status'])));
 const dealClients=new Map<string,MondayItem[]>();for(const d of deals){const k=d.fields['Normalized Client Key']?.trim();if(k)dealClients.set(k,[...(dealClients.get(k)||[]),d])}
 const woClients=new Set(workOrders.map(w=>w.fields['Normalized Client Key']?.trim()).filter((x):x is string=>Boolean(x)));const matched=[...woClients].filter(k=>dealClients.has(k));const openActive=new Set<string>();for(const w of activeWork){const k=w.fields['Normalized Client Key']?.trim();if(k&&(dealClients.get(k)||[]).some(d=>['open','on hold'].includes(norm(d.fields['Deal Status']))))openActive.add(k)}
 const dealFlagged=dealsRaw.filter(d=>d.fields['Data Quality Flags']?.trim()).length;const workOrderFlagged=workOrders.filter(w=>w.fields['Data Quality Flags']?.trim()).length;const totalRows=dealsRaw.length+workOrders.length;const score=totalRows?Math.max(0,Math.round(((totalRows-dealFlagged-workOrderFlagged)/totalRows)*100)):0;
 return {generatedAt:new Date().toISOString(),deals:{sourceCount:dealsRaw.length,validCount:deals.length,openCount:deals.filter(d=>norm(d.fields['Deal Status'])==='open').length,wonCount:wonDeals.length,deadCount:deals.filter(d=>norm(d.fields['Deal Status'])==='dead').length,onHoldCount:deals.filter(d=>norm(d.fields['Deal Status'])==='on hold').length,pipelineValue:openDeals.reduce((s,d)=>s+money(d.fields['Masked Deal value']),0),wonValue:wonDeals.reduce((s,d)=>s+money(d.fields['Masked Deal value']),0),bySector:groupMoney(openDeals,'Sector/service'),byStage:groupMoney(openDeals,'Deal Stage')},workOrders:{count:workOrders.length,completed:workOrders.filter(w=>norm(w.fields['Execution Status'])==='completed').length,ongoing:workOrders.filter(w=>/ongoing|current month/.test(norm(w.fields['Execution Status']))).length,notStarted:workOrders.filter(w=>norm(w.fields['Execution Status'])==='not started').length,atRisk:atRisk.length,receivable:workOrders.reduce((s,w)=>s+money(w.fields['Amount Receivable']),0),billedValue:workOrders.reduce((s,w)=>s+money(w.fields['Billed Value Incl GST']),0),collectedValue:workOrders.reduce((s,w)=>s+money(w.fields['Collected Amount Incl GST']),0),bySector:groupCount(workOrders,'Sector'),byStatus:groupCount(workOrders,'Execution Status')},crossBoard:{matchedClients:matched.length,totalWorkOrderClients:woClients.size,clientsWithOpenDealsAndActiveWork:openActive.size},dataQuality:{score,dealFlagged,workOrderFlagged,totalRows}};
}
export function formatMoney(value:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value)}
