import type { Deal, WorkOrder } from "../src/types/index";

export function makeDeal(overrides: Partial<Deal> = {}): Deal {
  return {
    mondayItemId: "deal-1",
    name: "Deal 1",
    ownerCode: "OWNER_001",
    clientCode: "COMPANY001",
    normalizedClientKey: "COMPANY001",
    status: "Open",
    closeDate: null,
    closureProbability: "High",
    value: 100,
    tentativeCloseDate: "2026-09-30",
    stage: "E. Proposal/Commercials Sent",
    productDeal: "Pure Service",
    sector: "Mining",
    createdDate: "2026-01-01",
    sourceRow: 1,
    sourceQualityFlags: [],
    malformed: false,
    ...overrides,
  };
}

export function makeWorkOrder(overrides: Partial<WorkOrder> = {}): WorkOrder {
  return {
    mondayItemId: "wo-1",
    name: "WO-1",
    customerCode: "WOCOMPANY_001",
    normalizedClientKey: "COMPANY001",
    serialNumber: "WO-1",
    natureOfWork: "One time Project",
    lastExecutedMonth: null,
    executionStatus: "Ongoing",
    dataDeliveryDate: null,
    poDate: "2026-01-01",
    documentType: "Purchase Order",
    probableStartDate: "2026-01-10",
    probableEndDate: "2026-10-01",
    bdKamPersonnelCode: "OWNER_001",
    sector: "Mining",
    typeOfWork: "Volumetric survey",
    softwarePlatform: "NONE",
    lastInvoiceDate: null,
    latestInvoiceNumber: null,
    amountExclGst: 100,
    amountInclGst: 118,
    billedValueExclGst: 50,
    billedValueInclGst: 59,
    collectedAmountInclGst: 30,
    amountToBeBilledExclGst: 50,
    amountToBeBilledInclGst: 59,
    amountReceivable: 29,
    arPriority: null,
    quantityByOps: 10,
    quantitiesAsPerPo: "10",
    quantityBilledTillDate: 5,
    balanceQuantity: 5,
    invoiceStatus: "Partially Billed",
    expectedBillingMonth: "Sep",
    actualBillingMonth: null,
    actualCollectionMonth: null,
    woStatusBilled: "Open",
    collectionStatus: null,
    collectionDate: null,
    billingStatus: "Partially Billed",
    sourceRow: 1,
    sourceQualityFlags: [],
    malformed: false,
    ...overrides,
  };
}
