/**
 * monday column IDs are schema identifiers, not data. Keeping them centralized
 * makes schema drift explicit while all row values continue to be fetched live.
 */
export const DEAL_COLUMN_IDS = {
  ownerCode: "text_mm6jk692",
  clientCode: "text_mm6jjyjh",
  status: "color_mm6j5fgz",
  closeDate: "date_mm6jmtdk",
  closureProbability: "dropdown_mm6jkmk8",
  value: "numeric_mm6jbwhe",
  tentativeCloseDate: "date_mm6jh16t",
  stage: "dropdown_mm6j2wnt",
  productDeal: "dropdown_mm6jg4q",
  sector: "dropdown_mm6j890p",
  createdDate: "date_mm6jb2vp",
  sourceRow: "numeric_mm6jev8d",
  normalizedClientKey: "text_mm6j60xc",
  dataQualityFlags: "long_text_mm6j7b54",
} as const;

export const WORK_ORDER_COLUMN_IDS = {
  customerCode: "text_mm6javb9",
  serialNumber: "text_mm6j4bj3",
  natureOfWork: "dropdown_mm6j14xj",
  lastExecutedMonth: "text_mm6jd8j5",
  executionStatus: "color_mm6jh8zp",
  dataDeliveryDate: "date_mm6je9w1",
  poDate: "date_mm6jzn82",
  documentType: "dropdown_mm6jfdp",
  probableStartDate: "date_mm6jtmf",
  probableEndDate: "date_mm6jjg65",
  bdKamPersonnelCode: "text_mm6jpne1",
  sector: "dropdown_mm6jpft6",
  typeOfWork: "dropdown_mm6jhhqg",
  softwarePlatform: "dropdown_mm6j1hgy",
  lastInvoiceDate: "date_mm6jzmnw",
  latestInvoiceNumber: "text_mm6j726t",
  amountExclGst: "numeric_mm6jwjes",
  amountInclGst: "numeric_mm6j7saa",
  billedValueExclGst: "numeric_mm6j876e",
  billedValueInclGst: "numeric_mm6jvr5n",
  collectedAmountInclGst: "numeric_mm6jby91",
  amountToBeBilledExclGst: "numeric_mm6j5bf2",
  amountToBeBilledInclGst: "numeric_mm6jfnrz",
  amountReceivable: "numeric_mm6j6g2p",
  arPriority: "color_mm6jj41e",
  quantityByOps: "numeric_mm6j41w4",
  quantitiesAsPerPo: "text_mm6j54zp",
  quantityBilledTillDate: "numeric_mm6jzt3h",
  balanceQuantity: "numeric_mm6jrhwa",
  invoiceStatus: "color_mm6jvfw8",
  expectedBillingMonth: "text_mm6jh731",
  actualBillingMonth: "text_mm6j6vj8",
  actualCollectionMonth: "text_mm6jh1th",
  woStatusBilled: "color_mm6jeqyz",
  collectionStatus: "text_mm6j5yex",
  collectionDate: "text_mm6j1670",
  billingStatus: "color_mm6jhv83",
  sourceRow: "numeric_mm6j2wrs",
  normalizedClientKey: "text_mm6j8tck",
  dataQualityFlags: "long_text_mm6j9xs0",
} as const;
