import type { MetricDefinition, MetricId } from "./types";

const V1 = "1.0.0" as const;
const DEAL_DIMENSIONS = ["sector", "stage", "client", "quarter", "status"] as const;
const WORK_ORDER_DIMENSIONS = [
  "sector",
  "client",
  "work_order_status",
  "billing_status",
  "collection_status",
] as const;

export const SEMANTIC_METRICS: Record<MetricId, MetricDefinition> = {
  open_pipeline_value: {
    id: "open_pipeline_value",
    label: "Open pipeline value",
    description: "Sum of known Deal values for non-malformed Deals whose canonical status is Open.",
    unit: "INR",
    aggregation: "sum",
    nullSemantics: "Open Deals with null value remain in the open-deal population but contribute no monetary amount; they are reported as unknown-value records.",
    sourceEntities: ["deal"],
    validDimensions: [...DEAL_DIMENSIONS],
    coverageSemantics: {
      tracked: true,
      known: "Open Deals with a non-null normalized value.",
      unknown: "Open Deals with a null normalized value; excluded from the monetary sum but retained in coverage counts.",
    },
    semanticVersion: V1,
    canonicalAnalytics: "calculatePipelineMetrics",
    canonicalField: "openPipelineValue",
  },
  known_won_value: {
    id: "known_won_value",
    label: "Known won value",
    description: "Sum of known Deal values for non-malformed Deals whose canonical status is Won; not a claim of complete historical revenue.",
    unit: "INR",
    aggregation: "sum",
    nullSemantics: "Won Deals with null value contribute no monetary amount and remain explicitly unknown in coverage.",
    sourceEntities: ["deal"],
    validDimensions: [...DEAL_DIMENSIONS],
    coverageSemantics: {
      tracked: true,
      known: "Won Deals with a non-null normalized value.",
      unknown: "Won Deals with a null normalized value; excluded from known won value.",
    },
    semanticVersion: V1,
    canonicalAnalytics: "calculatePipelineMetrics",
    canonicalField: "wonValue",
  },
  receivables: {
    id: "receivables",
    label: "Receivables",
    description: "Sum of known normalized amount receivable values across non-malformed Work Orders.",
    unit: "INR",
    aggregation: "sum",
    nullSemantics: "Work Orders with null amountReceivable contribute no amount and are counted as unknown receivable records.",
    sourceEntities: ["work_order"],
    validDimensions: [...WORK_ORDER_DIMENSIONS],
    coverageSemantics: {
      tracked: true,
      known: "Usable Work Orders with non-null amountReceivable.",
      unknown: "Usable Work Orders with null amountReceivable; excluded from the sum.",
    },
    semanticVersion: V1,
    canonicalAnalytics: "calculateWorkOrderHealth",
    canonicalField: "receivables",
  },
  total_work_order_value: {
    id: "total_work_order_value",
    label: "Total Work Order value",
    description: "Sum of known Work Order amountInclGst values across non-malformed Work Orders.",
    unit: "INR",
    aggregation: "sum",
    nullSemantics: "Work Orders with null amountInclGst contribute no amount and are counted as unknown amount records.",
    sourceEntities: ["work_order"],
    validDimensions: [...WORK_ORDER_DIMENSIONS],
    coverageSemantics: {
      tracked: true,
      known: "Usable Work Orders with non-null amountInclGst.",
      unknown: "Usable Work Orders with null amountInclGst; excluded from the sum.",
    },
    semanticVersion: V1,
    canonicalAnalytics: "calculateWorkOrderHealth",
    canonicalField: "totalAmountInclGst",
  },
  billed_value: {
    id: "billed_value",
    label: "Billed value",
    description: "Sum of known billedValueInclGst values across non-malformed Work Orders.",
    unit: "INR",
    aggregation: "sum",
    nullSemantics: "Null billedValueInclGst values contribute no amount; lineage reports them as unknown for this metric.",
    sourceEntities: ["work_order"],
    validDimensions: [...WORK_ORDER_DIMENSIONS],
    coverageSemantics: {
      tracked: true,
      known: "Usable Work Orders with non-null billedValueInclGst.",
      unknown: "Usable Work Orders with null billedValueInclGst; excluded from the sum.",
    },
    semanticVersion: V1,
    canonicalAnalytics: "calculateWorkOrderHealth",
    canonicalField: "billedValueInclGst",
  },
  collected_value: {
    id: "collected_value",
    label: "Collected value",
    description: "Sum of known collectedAmountInclGst values across non-malformed Work Orders.",
    unit: "INR",
    aggregation: "sum",
    nullSemantics: "Null collectedAmountInclGst values contribute no amount; lineage reports them as unknown for this metric.",
    sourceEntities: ["work_order"],
    validDimensions: [...WORK_ORDER_DIMENSIONS],
    coverageSemantics: {
      tracked: true,
      known: "Usable Work Orders with non-null collectedAmountInclGst.",
      unknown: "Usable Work Orders with null collectedAmountInclGst; excluded from the sum.",
    },
    semanticVersion: V1,
    canonicalAnalytics: "calculateWorkOrderHealth",
    canonicalField: "collectedAmountInclGst",
  },
  to_be_billed: {
    id: "to_be_billed",
    label: "Amount to be billed",
    description: "Sum of known amountToBeBilledInclGst values across non-malformed Work Orders.",
    unit: "INR",
    aggregation: "sum",
    nullSemantics: "Null amountToBeBilledInclGst values contribute no amount; lineage reports them as unknown for this metric.",
    sourceEntities: ["work_order"],
    validDimensions: [...WORK_ORDER_DIMENSIONS],
    coverageSemantics: {
      tracked: true,
      known: "Usable Work Orders with non-null amountToBeBilledInclGst.",
      unknown: "Usable Work Orders with null amountToBeBilledInclGst; excluded from the sum.",
    },
    semanticVersion: V1,
    canonicalAnalytics: "calculateWorkOrderHealth",
    canonicalField: "amountToBeBilledInclGst",
  },
  open_deal_count: {
    id: "open_deal_count",
    label: "Open deal count",
    description: "Count of non-malformed Deals whose canonical status is Open.",
    unit: "count",
    aggregation: "count",
    nullSemantics: "Deal monetary value is irrelevant to this count; malformed Deals are excluded by canonical analytics.",
    sourceEntities: ["deal"],
    validDimensions: [...DEAL_DIMENSIONS],
    coverageSemantics: {
      tracked: false,
      known: "All included Open Deals count regardless of value completeness.",
      unknown: "Not applicable to the count metric.",
    },
    semanticVersion: V1,
    canonicalAnalytics: "calculatePipelineMetrics",
    canonicalField: "openDeals",
  },
  won_deal_count: {
    id: "won_deal_count",
    label: "Won deal count",
    description: "Count of non-malformed Deals whose canonical status is Won.",
    unit: "count",
    aggregation: "count",
    nullSemantics: "Deal monetary value is irrelevant to this count; malformed Deals are excluded by canonical analytics.",
    sourceEntities: ["deal"],
    validDimensions: [...DEAL_DIMENSIONS],
    coverageSemantics: {
      tracked: false,
      known: "All included Won Deals count regardless of value completeness.",
      unknown: "Not applicable to the count metric.",
    },
    semanticVersion: V1,
    canonicalAnalytics: "calculatePipelineMetrics",
    canonicalField: "wonDeals",
  },
  active_work_order_count: {
    id: "active_work_order_count",
    label: "Active Work Order count",
    description: "Count of non-malformed Work Orders classified as ongoing, not started, paused, or active-other by canonical Work Order status logic.",
    unit: "count",
    aggregation: "count",
    nullSemantics: "Monetary nulls do not affect this count; Work Orders outside canonical active status buckets are excluded.",
    sourceEntities: ["work_order"],
    validDimensions: [...WORK_ORDER_DIMENSIONS],
    coverageSemantics: {
      tracked: false,
      known: "All Work Orders included by the canonical active-status classifier.",
      unknown: "Not applicable to the count metric.",
    },
    semanticVersion: V1,
    canonicalAnalytics: "calculateWorkOrderHealth",
    canonicalField: "activeWorkOrders",
  },
};

export function getMetricDefinition(id: MetricId): MetricDefinition {
  return SEMANTIC_METRICS[id];
}

export function listMetricDefinitions(): MetricDefinition[] {
  return Object.values(SEMANTIC_METRICS);
}
