'use client';
import { FormEvent,useEffect,useMemo,useState } from 'react';
import type { DashboardData } from '@/lib/types';
const fmt=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0,notation:n>=10000000?'compact':'standard'}).format(n);
const prompts=['How is our pipeline looking?','Which projects are at risk?','Show collections and receivables','Which clients appear across both boards?','Prepare a leadership brief'];
type ChatMessage={role:'user'|'assistant';text:string;caveats?:string[]};
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article className="metric"><div className="metricLabel">{label}</div><strong>{value}</strong><span>{note}</span></article>}
function Bars({rows,money=false}:{rows:Array<{name:string;count?:number;value?:number}>;money?:boolean}){const max=Math.max(1,...rows.map(r=>money?(r.value||0):(r.count||0)));return <div className="bars">{rows.slice(0,6).map(r=>{const n=money?(r.value||0):(r.count||0);return <div className="barRow" key={r.name}><div><span>{r.name}</span><b>{money?fmt(n):n}</b></div><i><em style={{width:`${Math.max(4,n/max*100)}%`}}/></i></div>})}</div>}
export default function Dashboard(){
 const [data,setData]=useState<DashboardData|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [question,setQuestion]=useState('');const [sending,setSending]=useState(false);const [messages,setMessages]=useState<ChatMessage[]>([{role:'assistant',text:'I query the live monday.com Deals and Work Orders boards and calculate business metrics deterministically. Ask me a founder-level question.'}]);
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/dashboard',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}catch(e){setError(e instanceof Error?e.message:'Could not load live data.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);const updated=useMemo(()=>data?new Date(data.generatedAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):'—',[data]);
 const ask=async(message=question)=>{const text=message.trim();if(!text||sending)return;setMessages(m=>[...m,{role:'user',text}]);setQuestion('');setSending(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});const j=await r.json();setMessages(m=>[...m,{role:'assistant',text:r.ok?j.answer:`${j.error}${j.requestId?` (Request ${j.requestId})`:''}`,caveats:j.caveats}])}catch{setMessages(m=>[...m,{role:'assistant',text:'The request could not be completed. Please retry.'}])}finally{setSending(false)}};const submit=(e:FormEvent)=>{e.preventDefault();void ask()};
 return <main><header className="topbar"><div className="brand"><div className="logo">SC</div><div><b>Skylark Command</b><span>Founder Intelligence</span></div></div><div className="live"><i/> LIVE MONDAY DATA <small>Updated {updated}</small></div></header><section className="hero"><div><span className="eyebrow">EXECUTIVE CONTROL PLANE</span><h1>Business truth,<br/><em>without the spreadsheet hunt.</em></h1><p>Read-only intelligence across Deals and Work Orders, with transparent data-quality caveats.</p></div><button onClick={()=>void load()} disabled={loading}>{loading?'Syncing…':'Refresh live data'}</button></section>{error&&<div className="error">{error}<button onClick={()=>void load()}>Retry</button></div>}{data&&<><section className="metrics"><Metric label="ACTIVE PIPELINE" value={fmt(data.deals.pipelineValue)} note={`${data.deals.openCount} open · ${data.deals.onHoldCount} on hold`}/><Metric label="WON VALUE" value={fmt(data.deals.wonValue)} note={`${data.deals.wonCount} won deals`}/><Metric label="WORK ORDERS" value={String(data.workOrders.count)} note={`${data.workOrders.completed} completed · ${data.workOrders.ongoing} active`}/><Metric label="RECEIVABLES" value={fmt(data.workOrders.receivable)} note={`${data.workOrders.atRisk} explicitly at-risk`}/><Metric label="DATA HEALTH" value={`${data.dataQuality.score}%`} note={`${data.dataQuality.dealFlagged+data.dataQuality.workOrderFlagged} rows flagged`}/></section><section className="grid"><article className="panel wide"><div className="panelHead"><div><span>SALES</span><h2>Active pipeline by sector</h2></div><b>{data.deals.openCount+data.deals.onHoldCount} opportunities</b></div><Bars rows={data.deals.bySector} money/></article><article className="panel"><div className="panelHead"><div><span>OPERATIONS</span><h2>Execution health</h2></div></div><Bars rows={data.workOrders.byStatus}/></article><article className="panel"><div className="panelHead"><div><span>CROSS-BOARD</span><h2>Account intelligence</h2></div></div><div className="bigStat">{data.crossBoard.matchedClients}<small>matched clients</small></div><p>{data.crossBoard.clientsWithOpenDealsAndActiveWork} accounts have both active work and open/on-hold opportunities.</p></article></section></>}
 <section className="copilot"><div className="copilotIntro"><span className="eyebrow">FOUNDER COPILOT</span><h2>Ask the business.</h2><p>Calculations are performed in code from live monday.com records; the agent explains the result and surfaces caveats.</p><div className="promptList">{prompts.map(p=><button key={p} onClick={()=>void ask(p)}>{p}<span>↗</span></button>)}</div></div><div className="chat"><div className="messages">{messages.map((m,i)=><div className={`msg ${m.role}`} key={i}><span>{m.role==='assistant'?'COMMAND':'YOU'}</span><p>{m.text}</p>{m.caveats?.length?<small>⚠ {m.caveats.join(' ')}</small>:null}</div>)}{sending&&<div className="msg assistant"><span>COMMAND</span><p className="typing">Querying monday.com…</p></div>}</div><form onSubmit={submit}><input maxLength={700} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about pipeline, sectors, operations, collections…"/><button disabled={sending||!question.trim()}>Ask →</button></form></div></section><footer><span>Skylark Command</span><p>Read-only prototype · Live monday.com queries · No source data hardcoded</p></footer></main>;
}
